language: ruby
rvm:
- 2.0.0
services: postgresql
bundler_args: --without development --path=~/.bundle
install: touch ~/do_not_run_bundle
before_script:
- psql -c 'create database test;' -U postgres
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:schema:load
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler bundle_cache
- bundle_cache_install
script:
- bundle exec rspec
- bundle exec cucumber
after_script:
- bundle_cache
env:
  global:
  - BUNDLE_ARCHIVE="bundle_for_travis"
  - AWS_S3_BUCKET="publishist-dev"
  - secure: HAhPP5zwXa+uZa3MuBT69njbuABoDu4BISUcbbPjgvTwrPBEn3dMjCio0YQyYxfGAEIPA2p8EXKGrDIXofRPqhi6xT4WuEwebCtao4Q8Z0T+mCNeRIKN062XQ/RVg6GiezCUOW8vuYYJadNhkDuqlWXoaOyY2wqW/AgaughDQMY=
  - secure: Ju3gMjMpcWjeUolvCcOjcyM7b3hdB7f7Nk5JkAiiWC0Jmn34fKLacN3NvvfAJqfAc9tNiMoRTC7Jqm9WSDoR8+TQNJBVzx5dBbh9hG3ABrksAB0AeHfSmaFoURp0WwCaRg0j0vahWuZldXI3AAjLE24RtdazAJXRItlAZ9NKii4=
  - secure: iFDxIRuPRAqCRkVpE/fnduNPZ7ljxA7K+l9PUEtHlxU4tlEEAmDQSI5OoyUINXg1/Y8lG4u/cEX4V2WyRRfVYShClZU5e/NSxmpO0ENYkBC6z9b03B5n0/zJtvky3A5/oR8tCG/PYW4DVJe22ZAIIuQNQ7TW0eTJQMLu5BCnXDA=
